inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "spec/support/**/*"
    - "spec/schema.rb"
    - "spec/db/migrate/*"
    - "spec/rails_helper.rb"
    - "spec/spec_helper.rb"
    - "db/schema.rb"
    - "db/migrate/*"
    - "config/**/*"
    - "bin/*"
    - "Gemfile"
    - "Gemfile.lock"
    - "Rakefile"
    - "config.ru"
    - "vendor/bundle/**/*"
    - "lib/tasks/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

# Max memoized
RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false
