---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sessions":
    post:
      summary: Login Auth
      tags:
      - Sessions
      parameters: []
      responses:
        '200':
          description: Auth Success
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: authorization
      in: header
